### PR TITLE
adding codeql

### PR DESCRIPTION
**Pull request by ezcater-scraven**
Adding config file to enable SAST scanning.

Please reach out via slack to #project-enable-sast if you have any questions or concerns.

### CODE REVIEW

**Comment by phantasm66** [comment]
Hmmmmm.... So, this is a forked repo we use. It rarely gets resynced with the upstream. I suspect as CodeQL signatures, etc.. stay current, it will fire when this workflow runs (every Tuesday night). This is a huge repository with tons of stuff we don't use. It might be a bit cumbersome to enable CodeQL on this forked repo.

Other SREs have any thoughts?

**Comment by corymurphy** [comment]
> Hmmmmm.... So, this is a forked repo we use. It rarely gets resynced with the upstream. I suspect as CodeQL signatures, etc.. stay current, it will fire when this workflow runs (every Tuesday night). This is a huge repository with tons of stuff we don't use. It might be a bit cumbersome to enable CodeQL on this forked repo.
> 
> Other SREs have any thoughts?

Do you know if we even use these charts from this repo, or do we use the upstream?

**Comment by phantasm66** [comment]
> > Hmmmmm.... So, this is a forked repo we use. It rarely gets resynced with the upstream. I suspect as CodeQL signatures, etc.. stay current, it will fire when this workflow runs (every Tuesday night). This is a huge repository with tons of stuff we don't use. It might be a bit cumbersome to enable CodeQL on this forked repo.
> > Other SREs have any thoughts?
> 
> Do you know if we even use these charts from this repo, or do we use the upstream?

The aggregator helm-charts, chart uses the upstream Bitnami chart. The forwarders one uses this fork (because the upstream does some weird stuff w/ a PSP that busts our implementation: https://github.com/ezcater/helm-charts/blob/main/charts/fluentd-forwarder/Chart.yaml).

**Review by phantasm66 — APPROVED** [review]
@ezcater-scraven it actually [looks OK for CodeQL scanning](https://github.com/ezcater/bitnami-charts/actions/runs/6086994072/job/16514603242?pr=6) (for now), so we can probably just go ahead with this.

**Pull request merged**
